### ISSUE TITLE
タグを記事のトップに配置したい

### ISSUE THREAD

**Issue by KaiseiYokoyama** [AmusementCreators/WebSite#21]
現状、タグは記事の下部に配置されている( 写真は https://www.amusement-creators.info/post/news/sohosai2019/ )。

<img width="834" alt="スクリーンショット 2019-11-06 18 31 32" src="https://user-images.githubusercontent.com/8509057/68286010-ada33b00-00c3-11ea-9e5b-510b800c6103.png">

置くならこのどこか?

<img width="732" alt="スクリーンショット 2019-11-06 18 35 18" src="https://user-images.githubusercontent.com/8509057/68286317-3d48e980-00c4-11ea-8c65-62091f1631f0.png">

**Comment by argonism** [comment]
このどっちかあたりが良さそうだと思いますね。
1.
<img width="1163" alt="スクリーンショット 2019-11-07 13 58 00" src="https://user-images.githubusercontent.com/44169535/68361460-48088a80-0167-11ea-81ff-06cccd8fad3c.png">
2.
<img width="1163" alt="スクリーンショット 2019-11-07 13 58 24" src="https://user-images.githubusercontent.com/44169535/68361618-e5fc5500-0167-11ea-8729-9a0bec125ca4.png">
