### ISSUE TITLE
Netlifyのプレビュー時に画像がうまく表示されないことがある

### ISSUE THREAD

**Issue by kuresugutaira** [AmusementCreators/WebSite#215]
具体的には
**画像**と**その画像へのパスを含む記事やニュース**を同時にpushしてプルリクを送ると画像を表示するURL先が存在せず、Netlifyでのプレビュー時に画像の表示ができない。

以下はプレビュー時のスクリーンショットであり、見て見ると`https:amusement-creator.info/images/sohosai2019/feature.img`に置いてある画像を持ってきて表示していることがわかる。
![image](https://user-images.githubusercontent.com/40123886/201313003-e2d3e531-f8b1-4217-b85b-62d9f064a0a8.png)

先述した状態のときにNetlifyのプレビューを見るとこのURL先が存在していないために画像が表示されないバグが発生しているものだと思われる。

**Comment by wraikny** [comment]
https://discourse.gohugo.io/t/correct-baseurl-on-netlify-previews/10429

**Comment by wraikny** [comment]
https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata

**Comment by wraikny** [comment]
https://github.com/AmusementCreators/WebSite/blob/cf921442c73dcd01e84bab960afd6ae6d2a70774/netlify.toml#L2

```diff
-   command = "hugo -DF" 
+   command = "hugo -DF -b $DEPLOY_URL" 
```
