### ISSUE TITLE
Twitterで表示されるサムネイルがarticleのfeatureではなくACアイコンになる

### ISSUE THREAD

**Issue by wraikny** [AmusementCreators/WebSite#24]
参考
https://twitter.com/ac_is_not_am/status/1192035308688179200?s=20

**Comment by KaiseiYokoyama** [comment]
それ仕様やねん

**Comment by KaiseiYokoyama** [comment]
デフォルトではACアイコンだけど、各記事に設定できたはず

**Comment by KaiseiYokoyama** [comment]
記事にimagesを指定すればいける……？

**Comment by wraikny** [comment]
wikiに記載お願いします！

**Comment by wraikny** [comment]
デフォルトでもアイコンだけはダサいのでHPの背景画像になる方がかっこいいと思う！

**Comment by KaiseiYokoyama** [comment]
デフォルトの画像を変更、修正の反映を確認 ref. https://cards-dev.twitter.com/validator
