### ISSUE TITLE
検索結果から/wikiを開いて飛ぶとNot Foundになってしまう

### ISSUE THREAD

**Issue by Funny-Silkie** [AmusementCreators/WebSite#38]
https://www.amusement-creators.info/wiki/ で開くとNot found

**Comment by KaiseiYokoyama** [comment]
以前のサイトの名残りがGoogleに残っているようですね

![スクリーンショット 2019-11-13 21 48 27](https://user-images.githubusercontent.com/8509057/68765098-5b33c280-065f-11ea-8e0a-43093a44590c.png)

ご報告ありがとうございます。リダイレクトで対応かな……？

**Comment by KaiseiYokoyama** [comment]
リダイレクト設定しました @Funny-Silkie さん, ご指摘ありがとう&お疲れさまでした 👍
