### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by wraikny** [AmusementCreators/WebSite#55]

**Comment by wraikny** [comment]
https://gohugo.io/content-management/syntax-highlighting/
標準機能にあった

**Comment by KaiseiYokoyama** [comment]
設定変えないと適用されないね

ref. https://monoworks.co.jp/post/2018-07-03-hugo-chroma-syntax-highlighter/

**Comment by wraikny** [comment]
こっちのfirefoxで反映されたけど

**Comment by KaiseiYokoyama** [comment]
？？　設定変えてないのに？

**Comment by wraikny** [comment]
リリースと設定が変わるのかは知らないけど、
`hugo server -D`
で
![image](https://user-images.githubusercontent.com/29581531/69496739-9912cf80-0f18-11ea-8772-011c8bd6c826.png)

**Comment by KaiseiYokoyama** [comment]
cargo.tomlとかの設定も変えずに?

**Comment by KaiseiYokoyama** [comment]
設定変更のシンタックスハイライトは確認できてないね……

**Comment by wraikny** [comment]
https://github.com/AmusementCreators/WebSite/blob/master/config.tomlのことなら何も変えてないよ。submoduleのテンプレートが影響してたりする？

**Comment by wraikny** [comment]
https://github.com/AmusementCreators/WebSite/blob/master/config.toml のことなら何も変えてないよ。submoduleのテンプレートが影響してたりする？

**Comment by KaiseiYokoyama** [comment]
`git submodule update --init --recursive` してみたけど変わらんな……firefoxにもしてみたけど同様

**Comment by argonism** [comment]
この本家プロジェクトで、れいにーさんの記事をarticles直下に入れた状態で確認したら、れいにーさんと同じようにハイライトされました。

**Comment by KaiseiYokoyama** [comment]
れいにーの記事ね、見てみます

**Comment by KaiseiYokoyama** [comment]
あ〜理解した、 `highlight` のショートコード (`{{< highlight hoge >}}{{< /highlight >}}`)使ってるのね

**Comment by KaiseiYokoyama** [comment]
手元の環境で`config.toml`に`pygmentsCodeFences = true`を設定したら、通常のmarkdownの```langnameでもハイライトがかかったので、shortcodeはあまり使わなくてもいいかも
行名とかが書けるので、まだ使い所はあるけど

**Comment by KaiseiYokoyama** [comment]
ショートコードを使わない普通のmarkdownの中のコードにもシンタックスハイライトを適用するように設定しました

<img width="646" alt="スクリーンショット 2019-11-26 19 04 12" src="https://user-images.githubusercontent.com/8509057/69619815-91216f80-107f-11ea-98e3-49c07e3fca6a.png">

**Comment by KaiseiYokoyama** [comment]
行数ってCSSで出せたりするかねぇ

**Comment by wraikny** [comment]
```の方が良かったのでありがたい！

**Comment by KaiseiYokoyama** [comment]
今からでも原稿の方を直しといてもらえるとgon君が助かるかもね（実際に聞いてみないと確実なことはわからんけど

**Comment by KaiseiYokoyama** [comment]
hugoの機能よりcode-prettify使うほうが使い勝手は良さそうなんだよなあ……

**Comment by KaiseiYokoyama** [comment]
でもそうなると確実にjs書くことになるからなあ……

**Comment by KaiseiYokoyama** [comment]
長いソースコードを貼る場合はGithubGist使うのが安定という感じがある
