### ISSUE TITLE
クローラを拒否している

### ISSUE THREAD

**Issue by wistnki** [AmusementCreators/WebSite#68]
ページヘッダに
`<meta name="ROBOTS" content="NOINDEX, NOFOLLOW">`
が挿入されているのでググっても出ないようになっている。

**Comment by KaiseiYokoyama** [comment]
https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/_default/baseof.html 10行目参照
```
    {{/* NOTE: For Production make sure you add `HUGO_ENV="production"` before your build command */}}
    {{ if eq (getenv "HUGO_ENV") "production" | or (eq .Site.Params.env "production")  }}
      <META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
    {{ else }}
      <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    {{ end }}
```

とのことで、

現在`hugo`コマンドでサイトをビルドしているところを、

- `HUGO_ENV="production" hugo`コマンドに変える
- 環境変数`HUGO_ENV`をなんとかして`"production"`に設定する

のどちらかで解決可能と思われる。

**Comment by KaiseiYokoyama** [comment]
@argonism の迅速かつ華麗な対応により、該当elementが

```html
<meta name="ROBOTS" content="INDEX, FOLLOW">
```

と更新されているのを確認 🎉

@wistnki @argonism お疲れさまでした 👍
