### ISSUE TITLE
サイト外へのurlはすべて新規タブで開くほうが良さそう

### ISSUE THREAD

**Issue by wraikny** [AmusementCreators/WebSite#7]

**Comment by KaiseiYokoyama** [comment]
a要素に`target="_blank"`つければいいのはわかるんだけど、サイト外なのかサイト内なのかを見分ける手段がわからん

**Comment by KaiseiYokoyama** [comment]
見っけた
https://blog.piyo.tech/posts/2018-03-29-hugo-blackfriday/
